### ISSUE TITLE
Migrate to Actions?

### ISSUE THREAD

**Issue by brentru** [adafruit/METROX-CircuitPython#5]
@ladyada  This older repo uses travis (https://travis-ci.org/github/adafruit/METROX-CircuitPython), should it get migrated to actions?

FWIW - It's not referenced in learn and code may not be up-to-date with CircuitPython

**Comment by ladyada** [comment]
it probably should be, i think travis will eventually completely go away...but its not a high priority!

**Comment by brentru** [comment]
Closing out as we're archiving this repository
